version: '3.8'

services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3306:3306
            - 33060:33060
        environment:
            MYSQL_DATABASE: TheBeerDb
            MYSQL_ROOT_PASSWORD: .753StrongPassword159.

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
    api:
        tty: true
        build: ./thebeerbookapi
        ports:
            - '4000:4000'
        depends_on:
            - db

    web:
        restart: always
        build:
            context: ./thebeerbookapp
            dockerfile: Dockerfile.prod
        ports:
            - '3000:80'
        depends_on:
            - api

    web_dev:
        restart: always
        build: ./thebeerbookapp
        ports:
            - '6006:6006'
        depends_on:
            - api
